# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from unittest import result
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 748)
        MainWindow.setMinimumSize(QtCore.QSize(457, 748))
        MainWindow.setMaximumSize(QtCore.QSize(457, 748))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputValue = QtWidgets.QLineEdit(self.centralwidget)
        self.inputValue.setGeometry(QtCore.QRect(10, 50, 441, 71))
        self.inputValue.setObjectName("inputValue")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 191, 41))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 24pt \"Old English Text MT\";")
        self.label.setObjectName("label")
        self.btnCalculated = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculated.setGeometry(QtCore.QRect(120, 160, 231, 91))
        self.btnCalculated.setStyleSheet("font: 24pt \"Parchment\";\n"
"font: 24pt \"Papyrus\";\n"
"color: rgb(0, 170, 127);\n"
"background-color: rgb(255, 255, 127);")
        self.btnCalculated.setObjectName("btnCalculated")
        self.showText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.showText.setGeometry(QtCore.QRect(20, 270, 421, 431))
        self.showText.setObjectName("showText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 457, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.btnCalculated.clicked.connect(self.calculated)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Calculator"))
        self.btnCalculated.setText(_translate("MainWindow", "Calculated"))

    def calculated(self):
        if(int(self.inputValue.text()) > 25): 
            self.showText.appendPlainText("Please Enter Number Less Than or Equal 25")
        else:
           self.showText.setPlainText("")
           results = self.inputValue.text()
           for i in range(1, 13, 1):
                calculated_value  = int(results) * i
                self.showText.appendPlainText(results +" x "+str(i) + " = " + str(calculated_value))
           self.inputValue.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
